### ISSUE TITLE
flatpak build problem

### ISSUE THREAD

**Issue by rderooy** [joncampbell123/dosbox-x#1976]
**Describe the bug**
Ok, that only took one release :-)

For some reason, that I'm not sure about the flatpak build process no longer works. The build seems to get stuck in a continuous loop. It seems it successfully does the autogen.sh and configure steps, then starts the make step and shows the following:

```
...
config.status: executing depfiles commands
Running: make
make: Warning: File 'Makefile.am' has modification time 1275 s in the future
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /run/build/dosbox-x/missing aclocal-1.16 
 cd . && /bin/sh /run/build/dosbox-x/missing automake-1.16 --foreign
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /run/build/dosbox-x/missing autoconf
/bin/sh ./config.status --recheck
running CONFIG_SHELL=/bin/sh /bin/sh ./configure --enable-core-inline --enable-debug=heavy --enable-sdl2 CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection --no-create --no-recursion
checking build system type... x86_64-pc-linux-gnu
...
```

And the configure and make just keeps looping.

**To Reproduce**
```
git clone --recursive https://github.com/flathub/com.dosbox_x.DOSBox-X.git
cd com.dosbox_x.DOSBox-X
flatpak install flathub org.freedesktop.Sdk//20.08 -y
flatpak-builder --force-clean --install --user -y builddir com.dosbox_x.DOSBox-X.yaml
```
**Additional context**
By default the yaml file will use buildsystem=autotool and that worked with the last version. I tried switching to buildsystem=simple and specifying the build-commands, but that also gets into the same circular configure issue.

e.g.
```
- name: dosbox-x
    buildsystem: simple
    build-commands:
      - ./autogen.sh
      - ./configure --enable-core-inline --enable-debug=heavy --enable-sdl2
      - make
      - make install
    sources:
      - type: archive
        url: https://github.com/joncampbell123/dosbox-x/archive/dosbox-x-v0.83.7.tar.gz
        sha256: 9cdfa3267c340a869255d8eb1c4ebf4adde47c22854e1d013da22190350bfbb3
    post-install:
      - install -Dm644 /app/share/icons/hicolor/scalable/apps/dosbox-x.svg /app/share/icons/hicolor/scalable/apps/${FLATPAK_ID}.svg
      - desktop-file-edit --set-key=Icon --set-value=${FLATPAK_ID} /app/share/applications/${FLATPAK_ID}.desktop
```

I also tried replacing the build-commands with just a simple ``./build-debug-sdl2`` and then it crashes out with a:

```
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... configure: error: newly created file is older than distributed files!
Check your system clock
Error: module dosbox-x: Child process exited with code 1
```

To clarify the flatpak build runs in an environment with EPOCH set to zero. This is intentional, and I don't think you can disable it.

Loop during regular build:
```

```
