### ISSUE TITLE
v2022.12.26 release doesn't come with Windows installers

### ISSUE THREAD

**Issue by Dobby233Liu** [joncampbell123/dosbox-x#3914]
### Describe the bug

Recent DOSBox-X releases usually come with Windows installer programs, however there are none released for v2022.12.26.

### Steps to reproduce the behaviour

1. Go to the [release's page](https://github.com/joncampbell123/dosbox-x/releases/tag/dosbox-x-v2022.12.26)
2. Notice the absence of `dosbox-x-winXX-2022.12.26-setup.exe`

### What operating system(s) this bug have occurred on?

Windows

### What version(s) of DOSBox-X have this bug?

v2022.12.26

### Additional information

I would also like to mention that among the released binaries, there are two Windows ARM builds and two Windows ARM64 builds. Were their inclusion accidental?

### Have you checked that no similar bug report(s) exist?

- [X] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

**Comment by Dobby233Liu** [comment]
There is also no `high-sierra` build, though that may be on purpose

**Comment by jvidalw** [comment]
Now the main pages features links to the installers for the latest build, but the files do not exist...

**Comment by jvidalw** [comment]
So? is this ever gonna be fixed?

**Comment by Dobby233Liu** [comment]
@joncampbell123 seems to suggest people to build the installers themselves, or smth.

> I've never personally made the Windows installer but the scripts are there for those who know how to use the Nullsoft installer.

(it doesn't actually use NSIS)~~

**Comment by Dobby233Liu** [comment]
Accidental close

**Comment by Torinde** [comment]
I hope somebody is able to automate running of the installers build scripts together with the creation of release ZIPs - I would assume many of the users who want the installers don't know how to build them.

**Comment by emendelson** [comment]
The person who made the installers no longer seems to be working on the project. You don't actually need the installer: just copy the executable wherever you want it.

**Comment by blindphoneman** [comment]
Well, where are those scripts, and, what does it take to build an installer?

I've played with NullSoft's installation system, but, it was over 15 years ago, if not more.

**Comment by Dobby233Liu** [comment]
> Well, where are those scripts, and, what does it take to build an installer?

A build script (*for Windows*), `build_windows_installer.bat`, is in the root of the repo. I think to use it, you
- Download Windows builds to `path/to/repo/release/windows`
- Open a cmd prompt in the root of the repo, and put `build_windows_installer`
- Find built installers at `contrib\windows\installer`

You don't need to install anything IIRC, as all build deps are in the repo. Note that you certainly want to change the MyProductVersion in `contrib\windows\installer\DOSBox-X-setup.iss` (and yeah, this does not use NSIS)

**Comment by Torinde** [comment]
> The person who made the installers no longer seems to be working on the project. You don't actually need the installer: just copy the executable wherever you want it.

Is this @Wengier ? Did he give any hints of the reason for stopping? I hope everything is fine and it's just temporary due to workload elsewhere...

**Comment by kcgen** [comment]
I've spoken with @Wengier over the past few days and everything is going very well for him, including having positive relations all of the fellow DOSBox community. I certainly don't want to speak on his behalf, but wish to alleviate any immediate concerns.

**Comment by JoeBroesele** [comment]
I think I have found a way to build the Windows installers from the latest release using the Github CI workflows. For the version 2022.12.26, renaming of the files the are not dated "20221226" is required.

Add the workflow `dosbox-x-windows-installers.yml`:
```
name: Build DOSBox-X Windows installers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-dosbox-x-windows-installers:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          repository: joncampbell123/dosbox-x
          path: .
      - name: Get DOSBox-X Windows builds.
        shell: bash
        run: |
          DOSBOX_X_RELEASE=`gh release --repo joncampbell123/dosbox-x list -L1 | awk '{print $3}' | sed -e "s/-/./g"`
          echo "DOSBOX_X_RELEASE=$DOSBOX_X_RELEASE" >> $GITHUB_ENV
          RELEASE_DIR="release\windows"
          mkdir -p $RELEASE_DIR
          cd $RELEASE_DIR
          gh release --repo joncampbell123/dosbox-x download -p 'dosbox-x-mingw-win*.zip' -p 'dosbox-x-vsbuild-*.zip'
          # The renaming should not be necessary, as all builds should have the same timestamp.
          mv dosbox-x-mingw-win32-20221227040728.zip dosbox-x-mingw-win32-20221226190454.zip
          mv dosbox-x-mingw-win32-lowend-20221227040427.zip dosbox-x-mingw-win32-lowend-20221226190454.zip
          mv dosbox-x-mingw-win64-20221227040641.zip dosbox-x-mingw-win64-20221226190454.zip
      - name: Build DOSBox-X Windows installers.
        shell: pwsh
        run: |
          $INSTALLER_DATE = echo ${{ env.DOSBOX_X_RELEASE }} | % { $_ -replace '\.', '' }
          .\build_windows_installer.bat $INSTALLER_DATE
      - name: Upload DOSBox-X Windows 32 bit installer.
        uses: actions/upload-artifact@v3
        with:
          name: dosbox-x-win32-${{ env.DOSBOX_X_RELEASE }}-setup.exe
          path: release\windows\dosbox-x-win32-${{ env.DOSBOX_X_RELEASE }}-setup.exe
      - name: Upload DOSBox-X Windows 64 bit installer.
        uses: actions/upload-artifact@v3
        with:
          name: dosbox-x-win64-${{ env.DOSBOX_X_RELEASE }}-setup.exe
          path: release\windows\dosbox-x-win64-${{ env.DOSBOX_X_RELEASE }}-setup.exe
```

It also works stand-alone, see here:
https://github.com/JoeBroesele/dosbox-x-installers/actions/
